### PR TITLE
Fixed issues with -stable

### PR DESCRIPTION
**Pull request by Eventyret**

### CODE REVIEW

**Review by viktor2097 — APPROVED** [review]

**Comment by viktor2097** [comment]
@vitalyliber Merge this pr, and create a release since this github action is currently not working.

**Comment by SimeonAleksov** [comment]
> @vitalyliber Merge this pr, and create a release since this github action is currently not working.

No reason for this message, please keep the PRs professional and clean.

**Comment by viktor2097** [comment]
> > @vitalyliber Merge this pr, and create a release since this github action is currently not working.
> 
> No reason for this message, please keep the PRs professional and clean.

Didn't know I would summon the github police.

**Comment by mschoettle** [comment]
Thanks for the fix @Eventyret. I can confirm that it works.

**Pull request merged**
