### PR TITLE
fix: add workspace to git safe directories to avoid dubious ownership error

### LINKED ISSUE #25: Deploy fails with dubious ownership error from git
Today our deploy pipeline failed with the following error:

```
Run vitalyliber/dokku-github-action@v6.2
Setting up SSH directory
Saving SSH key
fatal: detected dubious ownership in repository at '/github/workspace'
Enabling force deploy
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
Disabling host key checking
The deploy is starting
```

I see that this is coming from git ensuring that the ownership of parent directories do not differ (see: https://github.blog/2022-04-12-git-security-vulnerability-announced/). 

I don't fully understand how actions work but assume that this is happening in this action. Is it possible that the ownership differs between `/github/workspace/` vs. any of its parents? Not sure exactly why this happens now all of a sudden. It was working fine before today.

### PR DESCRIPTION
**Pull request by mschoettle**
Also switched the base image to `bullseye` at the same time.

Fixes #25

### CODE REVIEW

**Comment by mschoettle** [comment]
@vitalyliber Please review

**Comment by vitalyliber** [comment]
@mschoettle Thank you! I will review it today in the evening 👍

**Review by vitalyliber — APPROVED** [review]
Great job! 🥇

**Comment by vitalyliber** [comment]
@mschoettle thank you 🎄 🎅

**Comment by mschoettle** [comment]
Thanks a lot! Also for releasing a new release already 👍

**Comment by aalemayhu** [comment]
Thanks a lot for releasing this version 🙏🏾

**Pull request merged**
